### ISSUE TITLE
Include LibreOffice in the catalogue

### ISSUE THREAD

**Issue by deneb-alpha** [italia/developers-italia-backend#85]
The publiccode.yml file for LibreOffice is available here: 
https://github.com/tdf/libreoffice-metadata/blob/master/publiccode.yml

**Comment by libremente** [comment]
Thanks a lot @deneb-alpha! We'll keep you updated :+1:

**Comment by deneb-alpha** [comment]
hi @libremente, do you have any feedback?

**Comment by deneb-alpha** [comment]
> 
> 
> Thanks a lot @deneb-alpha! We'll keep you updated 👍

@libremente are there any issue with this publiccode?

**Comment by libremente** [comment]
Hi @deneb-alpha, sorry I thought I had already reported back to you, my bad.
Yes, we added your repo in the whitelist, however the validation failed. The problem is to be found in the way a third party library handles the final `+` in the SPDX license code. As such, @alranel wrote a patch to fix this issue which has not been merged yet (https://github.com/kyoh86/go-spdx/pull/2). Right now we are waiting for the patch to be merged in order to proceed with the creation of your entry. Sorry for the delay, I'll keep you updated 👍

**Comment by deneb-alpha** [comment]
Thanks for the update @libremente :)

**Comment by deneb-alpha** [comment]
hi @libremente, @alranel. Are there any news about this issue?

**Comment by deneb-alpha** [comment]
hi againg @libremente, @alranel, @ruphy. 
Are there any update?

**Comment by libremente** [comment]
Hi @deneb-alpha, the software is in the catalog right now. There is still an issue with the logo rendering but we are working on it. Thanks a lot! 👍

**Comment by deneb-alpha** [comment]
Thank you @libremente!
> 
> There is still an issue with the logo rendering but we are working on it. Thanks a lot! 👍

Is there something that I can fix directly for the logo?

**Comment by libremente** [comment]
Hi @deneb-alpha, don't worry, the problem is on our side but we are planning to fix it soon!

**Comment by libremente** [comment]
Linked to https://github.com/italia/developers-italia-backend/issues/95

**Comment by deneb-alpha** [comment]
Hi @libremente. 
The software is in the catalogue but the crawler is still not able to parse the proper version released by The Document Foundation. 
The listed version is 2019-09-05 (6.2.7) but the real last available version is 2019-10-17 (6.2.8).

**Comment by bfabio** [comment]
@libremente [This PR](https://github.com/alranel/go-vcsurl/pull/3) should fix it but

From go-vcsurl's [README.md](https://github.com/alranel/go-vcsurl/blob/master/README.md) reads
> Note that this library only performs syntactic checks and string manipulation, and it does not perform network calls to check that the given resources actually exist.

and that would not be true anymore with that patch. I'm wondering whether we should just move that logic to https://github.com/italia/publiccode-parser-go and respect go-vcsurl's philosophy. WDYT?

**Comment by libremente** [comment]
@bfabio Let's wait for the discussion with the repo maintainer and then will see.

**Comment by bfabio** [comment]
Reopening because it's still not updated.

**Comment by libremente** [comment]
Hi @deneb-alpha, sorry for the extreme delay but we still don't have a proper way to handle this case. We believe that in order to close this issue the best thing to do is to proceed as follows:
1. Change the `url` key in this `publiccode.yml` https://github.com/tdf/libreoffice-metadata/blob/d3080a56c432691d4e4b2e097126df81bd4870ac/publiccode.yml#L8 so that it points to the metadata repository itself.
2. Insert clear information in the metadata repo's README regarding the place where the code is actually store which is https://git.libreoffice.org/core.

[This PR](https://github.com/tdf/libreoffice-metadata/pull/2) should do it.
Let us know if this workaround makes sense for you.

**Comment by libremente** [comment]
Hi @deneb-alpha, let us know if the proposed solution may work. Thanks!
